# ---- Build stage ----
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o put_books_handler ./cmd/put_books.go

# ---- Run stage ----
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/put_books_handler ./put_books_handler
ENV DATABASE_URI=""
EXPOSE 3033
CMD ["./put_books_handler"] 