# ---- Build stage ----
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o post_books_handler ./cmd/post_books.go

# ---- Run stage ----
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/post_books_handler ./post_books_handler
ENV DATABASE_URI=""
EXPOSE 3032
CMD ["./post_books_handler"] 