# ---- Build stage ----
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o get_books_handler ./cmd/get_books.go

# ---- Run stage ----
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/get_books_handler ./get_books_handler
ENV DATABASE_URI=""
EXPOSE 3031
CMD ["./get_books_handler"] 